### ISSUE TITLE
limit and offset not working

### ISSUE THREAD

**Issue by an0nn30** [Raouf25/Spring-Boot-efficient-search-API#28]
Just was testing your API and noticed that the limit and offset parms are not working, however using the page headers work fine

**Comment by AnanthaRajuC** [comment]
+1 I too am facing the same issue.

**Comment by Raouf25** [comment]
Thank you 🙏   @an0nn30  and @AnanthaRajuC for your interaction.

I confirm the documentation is wrong. I have to fix it.
You can use pagination and size like this: 
`curl --location --request GET 'https://efficient-search-api.herokuapp.com/api/cars?country=USA&type=Small&sort=createDate,asc' \
--header 'Page-Number: 1' \
--header 'Page-Size: 5'`

Please feel free, If you have any feedback, suggestions, or a pull request.😊
